# Generated by Django 5.0.3 on 2026-05-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
