# Generated by Django 5.0.3 on 2026-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_profile_created_at_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
